import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getStudentRelatedRecords, cleanupAutoGeneratedEnrollments } from '@/lib/soft-delete-utils';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    
    console.log(`=== DEBUG: Analyzing student ${id} ===`);
    
    // Get student details
    const student = await prisma.student.findUnique({
      where: { id },
      include: {
        level: true,
        enrollments: {
          include: {
            classSection: {
              include: {
                subject: true
              }
            }
          }
        }
      }
    });
    
    if (!student) {
      return NextResponse.json({ error: 'Student not found' }, { status: 404 });
    }
    
    console.log(`Student found: ${student.firstName} ${student.lastName}, Level: ${student.level?.name}`);
    console.log(`Total enrollments: ${student.enrollments.length}`);
    
    // Get related records count
    const relatedRecords = await getStudentRelatedRecords(id);
    console.log('Related records:', relatedRecords);
    
    // Analyze each enrollment
    const enrollmentAnalysis = student.enrollments.map(enrollment => ({
      id: enrollment.id,
      classSectionName: enrollment.classSection?.name,
      subjectName: enrollment.classSection?.subject?.name,
      subjectLevelId: enrollment.classSection?.subject?.levelId,
      studentLevelId: student.levelId,
      isAutoGenerated: enrollment.classSection?.subject?.levelId === student.levelId
    }));
    
    console.log('Enrollment analysis:', enrollmentAnalysis);
    
    // Test cleanup function
    console.log('Testing cleanup function...');
    const cleanupResult = await cleanupAutoGeneratedEnrollments(id);
    console.log('Cleanup result:', cleanupResult);
    
    // Check enrollments after cleanup
    const remainingEnrollments = await prisma.enrollment.findMany({
      where: { studentId: id },
      include: {
        classSection: {
          include: {
            subject: true
          }
        }
      }
    });
    
    console.log(`Remaining enrollments after cleanup: ${remainingEnrollments.length}`);
    
    return NextResponse.json({
      student: {
        id: student.id,
        name: `${student.firstName} ${student.lastName}`,
        email: student.email,
        level: student.level?.name,
        levelId: student.levelId,
        isDeleted: student.isDeleted
      },
      relatedRecords,
      enrollmentAnalysis,
      cleanupResult,
      remainingEnrollmentsCount: remainingEnrollments.length,
      remainingEnrollments: remainingEnrollments.map(e => ({
        id: e.id,
        classSectionName: e.classSection?.name,
        subjectName: e.classSection?.subject?.name,
        isAutoGenerated: e.classSection?.subject?.levelId === student.levelId
      }))
    });
    
  } catch (error) {
    console.error('Debug endpoint error:', error);
    return NextResponse.json(
      { 
        error: 'Debug analysis failed',
        details: error instanceof Error ? error.message : 'Unknown error',
        stack: error instanceof Error ? error.stack : undefined
      },
      { status: 500 }
    );
  }
}