import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';
import { getStudentRelatedRecords } from '@/lib/soft-delete-utils';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    // Check if student exists
    const student = await prisma.student.findUnique({
      where: { id },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        levelId: true,
        isDeleted: true,
        deletedAt: true,
        deleteReason: true,
      },
    });

    if (!student) {
      return NextResponse.json(
        { error: 'Student not found' },
        { status: 404 }
      );
    }

    // Get related records
    const relatedRecords = await getStudentRelatedRecords(id);

    // Get detailed enrollment info
    const enrollments = await prisma.enrollment.findMany({
      where: { studentId: id },
      include: {
        classSection: {
          include: {
            subject: {
              select: { 
                name: true, 
                levelId: true 
              }
            }
          }
        }
      }
    });

    const payments = await prisma.studentPayment.findMany({
      where: { studentId: id },
      select: {
        id: true,
        amount: true,
        createdAt: true
      }
    });

    const attendances = await prisma.attendance.findMany({
      where: { studentId: id },
      select: {
        id: true,
        date: true,
        status: true
      },
      take: 5
    });

    return NextResponse.json({
      student,
      relatedRecords,
      enrollmentDetails: enrollments.map(e => ({
        id: e.id,
        subjectName: e.classSection?.subject?.name,
        subjectLevelId: e.classSection?.subject?.levelId,
        isAutoGenerated: e.classSection?.subject?.levelId === student.levelId
      })),
      paymentsCount: payments.length,
      attendancesCount: attendances.length,
      canSoftDelete: relatedRecords.payments === 0 && relatedRecords.attendances === 0,
      blockingReasons: [
        relatedRecords.payments > 0 && `Has ${relatedRecords.payments} payment records`,
        relatedRecords.attendances > 0 && `Has ${relatedRecords.attendances} attendance records`
      ].filter(Boolean)
    });
  } catch (error) {
    console.error('Error checking delete status:', error);
    return NextResponse.json(
      { error: 'Failed to check delete status' },
      { status: 500 }
    );
  }
}
